### PR TITLE
Website small updates

### PR DESCRIPTION
**Pull request by hakolao**
I think the website should no longer be green, but rather represent the color theme of Vulkano. I'm assuming that's what's in the logo.

Disclaimer: I am no web designer, but still thought that the website could be improved even with these small things

This PR:
- Adds some icons for faster navigation
- Updates the colors
- improves some textual parts and removes unnecessary "notes". E.g. on the front page, we should not be short selling vulkano. Even if the "goals" are not fully reached yet.
- Fixes some typos and edits the introduction etc. in the guide

I was thinking that perhaps the `Windowing` section could be replaced with a tutorial to make e.g. `interactive-fracal` or `game-of-life` or any traditional example that will showcase core loop, windowing, compute shaders and rendering pipelines.

So that's what I am going to do next (when I get a moment). But wanted to get started with these little tweaks.

### CODE REVIEW

**Review by ZakStar17 — APPROVED** [review]

**Comment by hakolao** [comment]
Seems there are conflicts, gonna resolve those...

**Review by AustinJ235 — APPROVED** [review]
Looks good!

**Comment by ZakStar17** [comment]
I think these are some good tweaks, the website feels more fresh, specially with the new icons.

I think we should leave the `Windowing` example. My plan was to make it use the triangle example from the main repository, in a way that it only explains core windowing (in a more theoretical way) and enhances the previous example. After that there could be a practical chapter that uses all the previous explained functionalities with a more complex project, like the examples you gave. This could be, for example, analagous to what the rust book does with the chapters like [these](https://doc.rust-lang.org/book/ch12-00-an-io-project.html).

I plan to add one or more chapters about 3d rendering, using the standard cube example. This would better explain buffers and the graphics pipeline, as well as introduce advanced topics like instancing (that feel more interactive).

**Comment by hakolao** [comment]
Sounds good @ZakStar17 !

**Pull request merged**
